name: multitenant-auth
services:
  app:
    image: app
    stdin_open: true
    container_name: app
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: ./compose/app/app.dockerfile
    entrypoint: /bin/sh /entrypoint.sh
    command: /bin/sh /start-app.sh
    env_file:
      - ./compose/envs/.app
      - ./compose/envs/.postgres
    volumes:
      - ./src:/app:cached
    environment:
      - PYTHONUNBUFFERED=1
      - DEPLOYMENT_MODE=dev
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONDONTWRITEBYTECODE=1
    networks:
      - backend-network

  postgres-db:
    image: postgres
    container_name: postgres-db
    volumes:
      - postgresdb:/var/lib/postgresql/data
    env_file:
      - ./compose/envs/.postgres
    ports:
      - "5433:5432"
    networks:
      - backend-network

volumes:
  postgresdb:

networks:
  backend-network:
    name: backend-network
    driver: bridge
