# Generated by Django 5.1.3 on 2024-11-24 09:47

from django.db import models, migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "price",
                    models.DecimalField(
                        db_default=0.0, decimal_places=2, default=0.0, max_digits=2
                    ),
                ),
                ("is_disabled", models.BooleanField(db_default=False, default=False)),
            ],
        ),
    ]
