# Generated by Django 5.1.3 on 2024-11-24 12:57

from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                db_default=0.0, decimal_places=2, default=0.0, max_digits=10
            ),
        ),
    ]
